title: Dynamic Macroeconomics Notes
description: A starter template for my class notes
theme: just-the-docs

url: https://github.com/icelaka/DynamicMacro_Notes

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
